sudo: false

language: node_js

env:
  - CXX=g++-4.8

node_js:
  - '7'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - mongodb
  - redis-server

before_install:
  - $CXX --version

script: npm test

after_script: npm run coverage